### PR TITLE
Use an issue form instead of an old-style issue template

### LINKED ISSUE #26: meta: add an issue form instead of current template
See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

### PR DESCRIPTION
**Pull request by hober**
Fixes #26.

### CODE REVIEW

**Review by marcoscaceres — APPROVED** [review]

**Comment by gsnedders** [comment]
It would've been better to move each of the things to be their own field!

**Comment by hober** [comment]
> It would've been better to move each of the things to be their own field!

Sounds cool! I'll try to figure out how to do that.

**Comment by nschonni** [comment]
https://github.com/WebKit/standards-positions/issues/26#issue-1295734689 points to the docs. You'd probably need to rename the file to `.yml`, and implement the fields through the `body:` properties

**Comment by hober** [comment]
PR is up: #162

**Pull request merged**
